### ISSUE TITLE
Fix VisibilityAggregator doc

### ISSUE THREAD

**Issue by ddseapy** [gchq/Gaffer#1042]
I could be wrong, but I think this line is incorrect:
https://github.com/gchq/Gaffer/blob/master/doc/src/main/java/uk/gov/gchq/gaffer/doc/dev/aggregator/VisibilityAggregator.java#L28

and should read:

```java
if ("private".equals(input1) || "private".equals(input2)) {
```

Another issue/confusion I found was the user-guide readme doesn't list visibility as an aggregated field for edge ingest (it does for entity). However the accumulo-store readme says it aggregates based on the entire key.  I'm guessing the user-guide is correct?

https://github.com/gchq/Gaffer/blob/master/doc/src/main/resources/user/walkthrough/Aggregation.md

https://github.com/gchq/Gaffer/blame/master/store-implementation/accumulo-store/README.md#L469).

Appologies if I'm wrong... still working on getting gaffer setup and reading docs.  Thanks.

**Comment by ddseapy** [comment]
Think that second point makes sense now.  I was confusing ingest aggregation with query aggregation.  Basically the aggregator is only really used at ingest time to group elements and doesn't use the accumulo combine iterator.

(https://github.com/gchq/Gaffer/blob/3bc134e920b1fb46e61a8fe2b333b495c14dd3ed/core/store/src/main/java/uk/gov/gchq/gaffer/store/util/AggregatorUtil.java#L48)

**Comment by p013570** [comment]
Ah another good spot, thanks @ddseapy! I'll fix that now.

Just in case you hadn't realised - that Aggregation markdown file you provided a link to is compiled and added to the Gaffer wiki here: https://github.com/gchq/Gaffer/wiki/User-Guide#aggregation.

The reason visibility isn't mentioned in the Aggregation section is mainly just because we don't introduce the concept of visibilities until later on in the Dev-Guide (just to keep things simpler). However, I will update the wording in the Dev-Guide visibility section to mention aggregation.

The Accumulo and HBase stores basically treat Visibility properties as another groupBy property (except it is stored in a different column). So at ingest it will not merge elements with different visibility values together. At query time Accumulo and HBase then effectively remove the Visibility property from the groupBy and summarises the elements with the different visibilities together.

For example:

You add these Edges:
```
1 -> 2   count = 1, visibility = "public"
1 -> 2   count = 2, visibility = "public"
1 -> 2   count = 10, visibility = "private"
1 -> 2   count = 20, visibility = "private"
```

These are persisted keeping the Edges with different visibilities separate, you can see the counts have been aggregated as they are not a groupBy property:
```
1 -> 2   count = 3, visibility = "public"
1 -> 2   count = 30, visibility = "private"
```

Then if a user with just "public" access to the system does a query they will just get back:
```
1 -> 2   count = 3, visibility = "public"
```

A user with "private" access, who by definition can also see "public" data, will get back both edges aggregated together:
```
1 -> 2   count = 33, visibility = "private"
```

**Comment by ddseapy** [comment]
Thanks, your explanation makes sense.

**Comment by t616178** [comment]
Merged into develop.
