### ISSUE TITLE
Multiple Data Types With AddElementsFromHDFS/SampleDataForSplitPoints

### ISSUE THREAD

**Issue by m316257** [gchq/Gaffer#1056]
The AddElementsFromHdfs and SampleDataForSplitPoints operations allow users to specify mutliple input paths but only a single mapperGenerator.

There will be situations where we want to add multiple data types (from different hdfs directories) to a Gaffer graph. We should be able to specify pairs of input path(s) to mappergenerators.

This will also be more efficient because we will be correctly sampling from the full data range for the table split points in Accumulo. And we can consolidate multiple bulk-loads into a single job.

**Comment by t616178** [comment]
Merged into develop.

**Comment by m55624** [comment]
# Migration notes

Within AddElementsFromHdfs and SampleDataForSplitPoints Input paths and MapperGenerators are now supplied as pairs, so multiple can be supplied.

Instead of using .inputPath() or inputPaths() along with a single .mapperGenerator() class name it is now possible to supply the inputPath and mapperGenerator as a pair, or map of multiple pairs.  You can do this by using addInputMapperPair(inputPath, mapperGeneratorClassName) or adding multiple as a map; addInputMapperPairs(Map<String, String> inputPath, mapperGeneratorClassName).
