### ISSUE TITLE
Question: Read time to spark RDD is slow

### ISSUE THREAD

**Issue by supamanda** [gchq/Gaffer#1233]
hi,
I'm using Gaffer to store data in Accumulo, and then reading out as a spark RDD using the provided  operations (eg GetAllRDDOfElements). Reading the data into an RDD seems to be really slow - it takes 2 hours to read 20 million records off a single node. No doubt some of it comes down to our hardware, but is this your experience as well?
Thanks for your help :)
Amanda

**Comment by gaffer01** [comment]
Hi,

That does seem slow. Accumulo is not optimised for reading all the data in a table, but it still seems a bit slow. We would say that reading all the data in a large table into an RDD will be so slow as to be unusable but 20 million records is not that much. Is this an Accumulo instance with just one server? Is the total table size 20 million records?

Is the performance ok when you're using a Spark operation like `GetRDDOfElements` with a seed so that it should only have to read a small amount of data that is relevant to the seed?

We're also working on improving the speed of Spark against Accumulo by adding an option to read Accumulo's Rfiles directly, rather than going via the tablet servers (see https://github.com/gchq/Gaffer/pull/1222). This requires the user running the Spark job to have read access to the files within the relevant table directory inside "/accumulo" (or wherever Accumulo is storing its data) in HDFS.

**Comment by supamanda** [comment]
We're running on Amazon. We have 11 EC2s (one is designated the master) each of which have hadoop, accumulo, and spark. The table I'm looking at has about 154 million records split over 13 tablets - the breakdown is 2x27million, 2x15million, 1x 843, and the rest between 5 and 12 million. (I know it has significant skew but I am not concerned with that at the moment because I'm interested in the limitations of the software.) When I set up the RDD with GetRDDOfAllElements and then do a count the total read time for the table is 3.1h - and this seems independent of the job config because I've tried increasing memory, and spreading over more executor boxes and the completion time is the same. The completion times of the tasks are (approx) 1s, 1.3min, 7.3min, 8.5min, 9.7min, 2x27min, 4x1.6h, 2h, 3.1h.

It's useful to know you don't recommend reading in the whole table - do you use an alternative input format to calculate summary statistics?

I just tried to count an RDD created with `GetRDDOfElements` and the id for the vertex. The result was 8 million. This split into 2 tasks the first took 1.7min, and the second took 41mins. So there's no improvement significant enough to be really usable. I'm storing the vertex names as strings - is that likely to have a significant effect?

Out of curiosity, I tried reading in the raw csv & tsv files and that completes in seconds. Maybe reading from the rfile will end up being closer to this kind of performance?

**Comment by gaffer01** [comment]
Thanks for the additional info. The total time to run the job is obviously dominated by the 3.1h which is to read the tablet with 27 million key-values. That works out as 2400 key-values read from the tablet server per second by a single Spark executor. Whether we'd expect better performance than that depends on lots of things: what networking you have, whether the tablet server has enough memory, how large the properties on the edges are, etc.

If you ran a compaction operation on the table then you'd get more balanced tablet sizes, and probably more tablets, which would improve the overall job time.

I wouldn't say "we don't recommend reading in the whole table" - it depends on your volumes and latency requirements. Very large tables will always take a long time to read. Your table is moderate size - it should be possible to read that quickly enough to be useful (but it would always be a batch job, rather than an interactive query).

We expect the performance of reading the Rfiles directly to be better than the current approach but only by a factor of 2-5.

I'd expect reading the raw csv files to be significantly faster than reading from Accumulo (but not seconds vs several hours).

We also have a Parquet store which is more designed to allow operations like `GetRDDOfAllElements` to run quickly - once the data is loaded in it is basically just reading the Parquet files directly from Spark. This store is still experimental - if you do use it please let us know how you get on.

We will do some performance tests of `GetAllRDDOfElements` to see what level of performance is normal.

Your 8 million results from using `GetRDDOfElements` for a single vertex is a lot! Using the standard Java API we easily get sub-second response for retrieving all the edges for a vertex when the vertex has a small (maybe up to thousands) number of edges. The Spark API might be a little slower as there is a small amount of overhead in starting executors. If there are 8 million edges then it could easily take a few minutes to return those. It shouldn't take 41 minutes though unless your tablet servers are under-resourced or there is some other bottleneck.

**Comment by m316257** [comment]
Hi @supamanda 
This does seem a very long time compared to what i've experienced on AWS (a few minutes for similarly sized datasets). 
I've been using EMR, not EC2, and installing Gaffer-Accumulo using slider (https://github.com/gchq/gaffer-tools/tree/master/slider) I think the latency is most likely due to building a hadoop/spark/accumulo cluster from EC2 nodes. 
I'm guessing (but could be wrong) that the network bandwidth between EC2 nodes is not as good as between nodes in an EMR cluster.
I'd suggest, if possible, trying the same on a similarly sized EMR cluster

**Comment by gaffer01** [comment]
Also see #1245: There is a bug with the `GetRDDOfAllElements` operation which means every edge is returned twice (each edge is stored twice in the Accumulo table so it can be found from either end), so the Spark executors are receiving twice as much data as they should. The `GetAllElements` operation in the standard Java API automatically makes sure it only returns each edge once.

It's not clear whether you'll get a 2x performance improvement when this bug is fixed - it depends whether the bottleneck is the networking between your Spark executor and the tablet server, or IO from your tablet server to the files or CPU in the tablet server.

**Comment by supamanda** [comment]
Thanks for your suggestions.

From what I can see in the doco, EMR runs on EC2s, so it probably won't make any difference. We're using r4.2xlarge for the data nodes and a m4.4xlarge for the name node, so it looks like these shouldn't have any real network bandwidth issues.
I did notice that the IP of the spark task executor rarely matches the IP of the accumulo tablet server it's reading from. Is there some config I have missed that will help them match up better?

The tablet server jvms each are allocated 2G max, I'm not sure whether that's reasonable or not, and I could probably beef them up a little. 

I tried re-ingesting the data which has reduced the skew somewhat but did not improve the performance at all. However, I noticed that the scan read rate fluctuates significantly (on the accumulo UI, the number in the query column sits on 800 for a while, then goes to 30K for a while and then back down to 800). Also, particular tablets are consistently slower than others. So I'm starting to wonder whether it's the data. I'm using netflow data (sourced from http://mcfp.weebly.com/the-ctu-13-dataset-a-labeled-dataset-with-botnet-normal-and-background-traffic.html) that I haven't aggregated on ingest so each edge is an event - which explains the 8 million result for a single vertex. There are 13 properties on each edge at this stage. I'm trying to pinpoint exactly where the slow parts are, and if it is actually consistent. Do you think it could be because the row id would be the same for all of those millions of edges?

**Comment by gaffer01** [comment]
>I did notice that the IP of the spark task executor rarely matches the IP of the accumulo tablet server it's reading from.

That's odd. You should get locality most of the time. I don't know why that is happening. It won't help the performance and as noted above without more information on the networking on the EC2 instances it's hard to know if network bandwidth is the limitation.

>The tablet server jvms each are allocated 2G max

That's a bit small. It would be worth increasing it if possible.

>I haven't aggregated on ingest so each edge is an event - which explains the 8 million result for a single vertex. I've tried to pinpoint exactly where the slow parts are (because the bad performance seemed to follow the data) and the scan rate slows dramatically when it is reading the millions of edges between the same vertices. Do you think it could be because the row id would be the same for all of those millions of edges?

I think if your schema is not doing aggregation and your data has millions of edges between the same 2 vertices then that will explain the unbalanced tablet sizes and that could explain the poor performance. The fact that the row id will be the same means that all the edges will be in the same tablet, so that work can't be parallelised.

We'd encourage you to think about using aggregation to replace the 8 million edges between the same 2 nodes with a summarised version. This could significantly reduce the data volumes.

If you can share your schema and generators for converting the raw data to elements, it's possible we could try the same experiments you're doing to see what the performance is.

**Comment by supamanda** [comment]
> You should get locality most of the time

I read that in both the accumulo doco and the spark doco, so was surprised that it wasn't happening for me. I've tried configuring the accumulo.properties with the zookeeper master address only and the entire list of cluster addresses but that doesn't make any different, so apart from writing some code for spark to try to use a specific tablet server I'm not really sure what else I could configure to force the locality. Any ideas on that?

> We'd encourage you to think about using aggregation to replace the 8 million edges between the same 2 nodes with a summarised version. This could significantly reduce the data volumes.
> 
> If you can share your schema and generators for converting the raw data to elements, it's possible we could try the same experiments you're doing to see what the performance is.

I have since looked at the data more closely and realised that there was likely a lot of overlap: https://mcfp.felk.cvut.cz/publicDatasets/CTU-13-Dataset/CTU-13-Dataset.tar.bz2 is processed already and the .netflow and .netflow.csv files from the first 6 CTU-Malware-Capture-Botnet at https://mcfp.felk.cvut.cz/publicDatasets/ are raw data, some of which may actually be in the first data set. The 8 million edges between 2 nodes are in the raw data and mostly seem to be accessing the google dns server, so in this case those edges are probably not useful anyway - though I guess it depends on your use case. 

I've attached my schema and generator [schema_and_generator.zip](https://github.com/gchq/Gaffer/files/1323028/schema_and_generator.zip) - it would be interesting to see whether you see any performance issues.

**Comment by supamanda** [comment]
FYI - my data locality issue was a spark config issue.

**Comment by supamanda** [comment]
I was also able to improve the scan time significantly (complete in 11 mins) by increasing the `table.scan.max.memory` and using the batch scan.

**Comment by gaffer01** [comment]
Excellent.

When you say "using a batch scanner" can you clarify what you mean? Which operation were you using and what were the options?

**Comment by supamanda** [comment]
I was using a copy of the `GetRDDOfAllElements` that I'd added the following line to:
`InputConfigurator.setBatchScan(AccumuloInputFormat.class, conf, true);`

**Comment by p013570** [comment]
@supamanda - that sounds like a great improvement. 

It would be good to get that change to the GetRDDOfAllElements included, either by default or as a configurable option.

We should also update the AccumuloStore README to add a some information to tell users to try and increase the value of the table.scan.max.memory property if they experience issues with the spark operations.

Would you be able to make those changes and contribute your changes back to Gaffer? You just need to sign our [contributors license](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0) and it might be worth having a quick look at our [ways of working](https://gchq.github.io/gaffer-doc/other/ways-of-working.html). Then just create a Pull Request from your forked Gaffer repository back into our develop branch.

If that is not possible, we could make the changes - just let us know.

**Comment by supamanda** [comment]
Good idea @p013570  - I'll work on it :)

**Comment by gaffer01** [comment]
@supamanda Thanks for this. We have the `setBatchScan` option on for `GetRDDOfElementsHandler` and `GetJavaRDDOfElementsHandler`, but not on for `GetRDDOfAllElements` as we believed that the batch scan option improved performance for range scans but not for full scans. If you have figures saying that it helps for `GetRDDOfAllElements` then we should change that, or at least make it an option.

**Comment by p013570** [comment]
Merged into develop.
