### ISSUE TITLE
Add support in the Parquet Store to natively handle the AgeOff predicate

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1303]
Without the native support of the AgeOff Predicate in the Parquet Store, all queries will need to be re-validated client side and it will make queries significantly slower.

**Comment by gaffer01** [comment]
The way this should work is:

- Validation should be applied to all elements when new data is added (as all the data has to be read anyway) - this should be optional though in case your application knows for sure that no invalid data has been added.
- There should be a `RemoveInvalidElements` operation that reprocesses the entire graph and removes invalid elements.
- All queries against the Parquet store should have an _optional_ option to validate the data before it is returned. There are scenarios where you know there isn't any invalid data, e.g. you do a nightly update to the graph which adds new data and removes old data and you then know that all queries that run in the next 24 hours won't see any invalid data (because all the data in the graph is now valid for the next 24 hours). In this case you want to avoid the expense of validation (the additional expense of doing validation could be very high if you're getting a data frame and then only reading one column - doing validation may require reading all the columns, converting to a Java `Element` object and applying a predicate).

**Comment by ac74475** [comment]
This looks like the same issue as #1100 to me. I agree with @gaffer01's explanation of how this should be implemented.

**Comment by p013570** [comment]
Yes I agree with @gaffer01. I've added this comment to #1100:

Currently the Parquet Store has special implementations for primitive predicates for some of Gaffer/Koryphe's core predicates like IsMoreThan. See ParquetFilterUtils.addPrimitiveFilter. I believe this means the IsMoreThan predicate can be applied more efficiently. AgeOff is just another predicate that is quite simple and #1303 is to add specific logic in ParquetFilterUtils to deal with the AgeOff predicate efficiently in a similar way to IsMoreThan.

So this issue is to simply add a bit of logic to handle the AgeOff Predicate in a similar way to IsMoreThan in ParquetFilterUtils.

**Comment by p013570** [comment]
This has been done as part of #1100.
