### ISSUE TITLE
FederatedStore missing schema

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1315]
Bug replication:
Via Rest
Route1
Create FederatedStore, with proxyGraph.
getSchema
returns "stuff"

Route2
Create empty FederatedStore
addGraph proxyGraph
getSchema
returns nothing **// WRONG!!!**

Add examine during gh-1304

**Comment by GCHQDeveloper404** [comment]
after #1318

**Comment by p013570** [comment]
This is due to the way the Graph class handles the schema. When the Graph is first initialised, the Graph class keeps a copy of the original schema. When a new graph is added to the FederatedStore, the Graph's original schema is not updated.

When you call graph.getSchema() or hit the graph/config/schema end point it actually returns this original schema instance.

To make it consistent, we could change it so that graph.getSchema always returns an empty schema for a federated store.

**Comment by p013570** [comment]
This has been fixed as a result of #1365
