### ISSUE TITLE
Common pattern needed for all Operations that return no results (empty, null or error)

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1332]
If GetElements is executed with no seeds, the handler throws an exception. If GetElements is executed without any data, then no results are returned. We just need to make sure this sort of logic is consistent across all Stores and Operations.

This was raised from work done on the Federated Store.

When access is invalid or unusual what are the expected and appropriate returns.
Check and test please.

getAllElements to graph that doesn't exist
getAllElements to graph with no access
getAllElements from empty graph.

**Comment by GCHQDeveloper404** [comment]
This requires discussion with users as to what they would expect with each action.
After:
gh-1322
gh-1231

**Comment by gaffer01** [comment]
The intention for the `GetElements` operation was that seeds have to be provided (i.e. not null, and if null is passed in then an exception is thrown), but if an empty set of seeds is passed in then an empty set of results is returned (it's quite common to query for an empty set of seeds if doing a breadth-first search expansion around a node and the next frontier is empty because you've already touched all the nodes in the component).

**Comment by GCHQDeveloper404** [comment]
getAllElements to graph that doesn't exist  -> exception is thrown
getAllElements to graph with no access -> exception is thrown
getAllElements from empty graph -> empty iterable is returned.
