### ISSUE TITLE
Merging Schema/Properties result in the ID being the graphID when different ids are detected

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1431]
current schema id = null
add schemaParentID = "a" 
current schema id = "a"
add schemaFile = "b"
if(id "a" and id "b" are different.) //check the id are same else rename to graphID
{current schema id = "graphId"}

Also always check that id doesn't already exist in library. if it does then check is schema is the same? 
if not throw exception.

similar for properties ids.

**Comment by GCHQDeveloper404** [comment]
Friday thinking, needs elaboration.

**Comment by m55624** [comment]
So we need a method within Graph that will update the graphId before the Schema or StoreProperties are updated.  This graphId can then be used within the updateStoreProperties() and updateSchema() to set the id's, using the graphId.  This will solve the issue within Graph, although the issue will still remain if a Schema or StoreProperties is added to a graph library not related to a Graph.

**Comment by m55624** [comment]
Logic has been updated to merge schema/storeProperties ID's rather than set them to null and then allow the GraphLibrary to deal with the null ID (which will then use the graph ID).  This is because a schema/storeProperties can be merged and added to a GraphLibrary without the use of a graph.  This would then throw an IllegalArgumentException as the ID is null.

**Comment by GCHQDeveloper404** [comment]
blocked whilst we consider removing schema and store properties IDs. See #1477.

**Comment by p013570** [comment]
Merged into develop.
