### ISSUE TITLE
Flink library only works with string inputs

### ISSUE THREAD

**Issue by javadev001001** [gchq/Gaffer#1454]
When using the Gaffer Flink library, the input from source must always be a string, otherwise it can't be handled by the string deserialisation schema.  You should be able to configure your own serialisation schemas.

**Comment by t616178** [comment]
@javadev001001 Do you need this for a particular use case, or is this just for information? We're trying to prioritise items in the backlog, so it would be handy to know.

**Comment by javadev001001** [comment]
No, this is for a specific use case.  We need to be able to handle byte[] input to the generator, rather than deserialising things as a string.

**Comment by m607123** [comment]
Current status:
Configurable implementation of GafferMapFunction, which is now abstract.
ByteArraySchema written to simply pass on the supplied byte[] rather than deserialise it.
Deprecated elementGenerator methods in AddElementsFromKafka, Socket and File, in favour of a wider generic implementation.

Issues with the AddElementsFromX integration tests, and the shallowClone could use some attention with regards to the 2 elementGenerator methods.
Extra tests in the AddElementsFromKafkaIT could do to be replicated in the IT's for Socket and File, once they are working.

**Comment by p013570** [comment]
Merged into develop.
