### ISSUE TITLE
Move OperationDetail and OperationField into own classes

### ISSUE THREAD

**Issue by m55624** [gchq/Gaffer#1793]
This will be a breaking change so needs to be done with a major release.

Currently OperationDetail and OperationField are inner classes within OperationServiceV2.  These should be in their own outer classes for ease of serialisation and consistency.

**Comment by g609bmsma** [comment]
Am I okay to tackle this one? Realise it says needs to be done with a major release and that it's a breaking change, so want to be careful

**Comment by g609bmsma** [comment]
So far I've refactored the two inner classes into their own outer classes with no errors in the code for any of the files. Upon testing, there's one failed test (shouldReturnOutputClassForOperationWithOutput in OperationServiceV2IT.java) which I'm currently trying to find the root cause of. Any ideas or suggestions would be appreciated.

**Comment by g609bmsma** [comment]
Think I've solved the issue, seems the issue was I needed to make some stuff protected instead of private. All tests passing so far, hope that continues.

**Comment by t92549** [comment]
This was actually done in #2336 but not tracked at the time
