### ISSUE TITLE
Replace Deprecated Authorisation Method

### ISSUE THREAD

**Issue by d47853** [gchq/Gaffer#2271]
When updating Github as part of a release, we make use of the Github API. To authenticate we use a Github Token. However the way in which we use the token is deprecated. See here for more detail: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

**Comment by arijitdatta** [comment]
As this is my first "contribution" ever, I would like to confirm the following. The change is only 1 and only to the deploy.sh file. Am I correct? If so, should I push the change? How will I know the change has worked?

**Comment by d47853** [comment]
Hi @arijitdatta!
Yeah that's right, it's a change to the ./cd/deploy.sh file. 
Start by creating a fork and making changes the deploy.sh on that fork.

To test the changes, create a dummy repository in Github with some labels on them (bug, headliner, enhancement, migration-required are the ones we use). Isolate the code that creates the release in deploy.sh (update the url so it now points at your dummy repository). Try running deploy.sh and check that it created a release.

Once satisfied that the changes work, push your changes and submit a pull request from your fork back to develop.

**Comment by arijitdatta** [comment]
Hi, 

I finished my changes. Also created the dummy repo with couple of issues.  Since I am on Win10, I installed cygwin to test out the script.

Running the deploy.sh file :
```
$ bash -x ./deploy.sh
+ set -e
+ repoName=Gaffer
+ repoId=Gaffer
+ artifactId=gaffer2
+ '[' '' == true ']'

```
The above is expected as it cannot get $RELEASE variable. Now if I try to isolate & run the part in deploy.sh file which creates the release, it will not work because it references RELEASE_VERSION.

So I created my own deploy.sh file locally my_deploy.sh, using the same constructs as the original deploy.sh file and hard coding the GITHUB TOKEN.  I have attached the my script for your perusal. 

I have pushed the the modified deploy.sh file into my forked repo. Once you confirm I will submit the pull request.


[my_deploy_sh.txt](https://github.com/gchq/Gaffer/files/4529512/my_deploy_sh.txt)

**Comment by d47853** [comment]
Good to hear it's working. The GITHUB_TOKEN, RELEASE and RELEASE_VERSION are all set in Travis which is probably why you're having trouble with them.

With the code, I noticed that the header and the "-H" option are separated by other options. To make it a bit more readable, it might be better to keep them together ie:
`curl -v -H <header> --data <body> <url>`

With the header itself it might be a good idea to keep it all together (and use double quotes to avoid literal processing of the variable) for example:
`-H "Authorization: token $GITHUB_TOKEN"` reads better than 
`-H 'Authorization: token'$GITHUB_TOKEN`. In the latter the $GITHUB_TOKEN could be read as being outside the header and there is no space between the "token" string and the token itself.

**Comment by arijitdatta** [comment]
Hi, 

Thanks for the detailed feedback. I should have taken literal processing into consideration. I have made the changes you requested & submitted a pull request.

**Comment by d47853** [comment]
Thanks @arijitdatta for working on this. It's now been merged into develop
