### ISSUE TITLE
Upgrade store integration tests to use JUnit 5

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2498]
The 21 integration tests within `integration-test/` extend [AbstractStoreIT](https://github.com/gchq/Gaffer/blob/23c323e894c8dba3e25029c3699b6fb5a050a39e/integration-test/src/test/java/uk/gov/gchq/gaffer/integration/AbstractStoreIT.java#L79).

The 6 store types within `store-implementation/` extend [AbstractStoreITs](https://github.com/gchq/Gaffer/blob/23c323e894c8dba3e25029c3699b6fb5a050a39e/integration-test/src/test/java/uk/gov/gchq/gaffer/integration/AbstractStoreITs.java#L44). The `AbstractStoreITs` are then ran with a custom extension of JUnit 4's `Suite`:
https://github.com/gchq/Gaffer/blob/23c323e894c8dba3e25029c3699b6fb5a050a39e/integration-test/src/test/java/uk/gov/gchq/gaffer/integration/AbstractStoreITs.java#L117

The `StoreTestSuite` collects all of the `AbstractStoreIT` subclasses and runs them all with the specified store properties from the AbstractStoreITs implementation. 

This works in JUnit 4 but is hard to replicate in JUnit 5. This is because Suites work differently, both using the current [workaround](https://junit.org/junit5/docs/5.7.2/user-guide/#running-tests-junit-platform-runner-test-suite) and the future release's [full implementation](https://junit.org/junit5/docs/5.8.0-M1/user-guide/#test-suite). More testing could be done with these options but I think we should look to change the structure of the operation ITs and their interaction with the various stores to make it less complicated.

This approach will probably be necessary anyway during the Gaffer 2 upgrade due to the huge changes coming to how Operations work in #2487.

**Comment by t92549** [comment]
Looks like some (or all) of this has been done in [develop-v2](https://github.com/gchq/Gaffer/tree/develop-v2), but I think this could be a Gaffer 1 issue

**Comment by t92549** [comment]
Of note: #2530 reverted a test back to JUnit4 to fix a strange test failure, this should be fixed. https://github.com/gchq/Gaffer/blob/0f76569a17ac953dbfd48a0e06f558721c32607c/store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGetTraitsTest.java#L22

**Comment by GCHQDeveloper314** [comment]
> Looks like some (or all) of this has been done in [develop-v2](https://github.com/gchq/Gaffer/tree/develop-v2), but I think this could be a Gaffer 1 issue

In that branch the integration tests have been completely restructured and pretty much rewritten from scratch. The changes seem to go far beyond those needed to work with JUnit 5.

It looks like the quickest approach might be to try and rework this rewritten version, although as it touches lots of different parts of Gaffer this would make for a pretty big diff - compared to trying to patch up the current version to work with JUnit 5.

At the moment, one of the reasons JUnit `Suite` is extended is to select which test classes to run. This was done because JUnit 4 didn't include a way to do this out of the box. JUnit 5 doesn't allow `Suite` to be extended like this, instead it has a concept of [Extensions](https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/extension/ExtendWith.html). This works differently and is probably not something we need to use because JUnit 5 does allow test classes to be included/excluded using an annotation.

The very minimum which needs to be done to replace JUnit 4 is to rework `AbstractStoreIT` & `AbstractStoreITs`, plus classes which implement these (store integration tests).

**Comment by GCHQDeveloper314** [comment]
I've now investigated this further, we should be able to migrate these tests to use JUnit 5 Suites. The `AbstractStoreITs` class will need to be reworked to strip out the custom functionality to configure which tests are run. This can potentially be replaced by an implementation of [BeforeTestExecutionCallback](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/BeforeTestExecutionCallback.html) which could perform the configuration for the Store. This would then be partly overridden by the actual Store tests in order to insert the relevant properties info. The Suite itself would be moved to the Store tests in order that the test classes to run could be configured on a per store basis - as this is done with annotations which cannot be changed at runtime.

The only problem seems to be with getting the failsafe plugin to recognise the JUnit 5 Suites.

**Comment by GCHQDeveloper314** [comment]
> > Look at the changes made in gh-2428 maybe the same/similar will work.
> 
> That PR took some tests out of the Store IT suite. We need to rework the whole suite to work properly with JUnit 5. When it is reworked, we could honestly move these standalone tests back to the store ITs and ensure they run properly to remove duplicate code.

Having looked at that issue & PR and the changes it made, I can see why those tests would have been run twice. This was because the tests were added to the Suite but also picked up by failsafe to be run independently of the suite - thereby running twice each. Some of them _may_ have simply shown up as skipped for the duplicate execution, but at least one looks like it would have run twice in full.

So far as I can tell, the changes in the PR to introduce `AbstractStandaloneFederatedStoreIT` are not required. The tests which depend on this class could be brought back under the normal `AbstractStoreIT` instead. This would mean changing `FederatedViewsIT` and `FederatedAdminIT` to extend `AbstractStoreIT` instead, excluding them from the default failsafe run (to prevent being run twice) and adding them back into the suite. `FederatedStoreRecursionIT` didn't need to be part of the suite at all and doesn't need to be changed.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2648
