### ISSUE TITLE
AssertJ withFailMessage() can't be last call

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2655]
AssertJ withFailMessage() can't be last call otherwise error is not displayed.

change
`assertThat(a).isEqual(b).withFailMesage(s)`
To
`assertThat(a).withFailMesage(s).isEqual(b)`

not limited to just `isEqual()` but with everything.

**Comment by GCHQDeveloper314** [comment]
Most instances of this can be found with the regex `\.withFailMessage\([^\(\)]*\));$` because `withFailMessage` at the end of the statement is never correct. That regex won't capture everything because bracket nesting is excluded as it's not possible to determine if brackets have been closed.

Can mostly be fixed by using Regex replace with `^(.*)(assertthat\(.*\))(\.(?:is|has|contain).*\(.*\))(\.withFailMessage\([^\(\)]*\));$` as the find and `$1$2$4$3;` as the replacement when everything is on one line and variants of this for multiple lines.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2656
