### ISSUE TITLE
Remove deprecated getSchema methods from store

### ISSUE THREAD

**Issue by lb324567** [gchq/Gaffer#2791]
Remove the deprecated getSchema method from abstract store. This is a continuation of the alpha 1 work #2552.
When deprecating getSchema you need to change it to the execute(getSchema) operation.

**Comment by lb324567** [comment]
Work started on this, branch: gh-2791-remove-deprecated-getSchema-methods-from-store

**Comment by GCHQDev404** [comment]
> Change the visibility of getSchema such that only the GetSchemaHandler can call it.

In reference to Stores like `MapStore` or `AccumuloStore` but not `ProxyStore` and `FederatedStore`

**Comment by GCHQDeveloper314** [comment]
After further examination it seems `getSchema` should not have been marked as deprecated. It cannot be removed and replaced with a getSchema operation because that operation is not equivalent to what the `getSchema` method does. The getSchema operation uses `getOriginalSchema`, except for if a compact schema is requested when it uses `getSchema` instead. The `getSchema` method cannot be replaced by `getOriginalSchema`, because these have different purposes:

- `getSchema()`: This gets the `schema` field from `Store`. This field is set by taking the input schema from the user and optimising it. [This removes unused types and adds default serialisers](https://github.com/gchq/Gaffer/blob/1f4eaed28f36b0ba4e1deb7923041b4f39c5497f/core/store/src/main/java/uk/gov/gchq/gaffer/store/schema/SchemaOptimiser.java#L49). After this optimisation has been done, **the value stored in the `schema` field is not the same as the schema used to create the store.** The schema used to create the store would **only** match the value in the `schema` field if it had no used types and included serialisers. 
- `getOriginalSchema()`: The gets the `originalSchema` field from `Store`. **When the _store_ is created this is not set**. It is set only from `Graph` (`build()` method of the Builder), where it is set to the schema used to build that graph. When creating a new graph with a schema, `originalSchema` will usually be the input schema from the user. When creating a new graph without a schema, the schema will be retrieved from somewhere else and could potentially be fetched from an existing `Store` using `getSchema`, in this case the `getSchema` and `getOriginalSchema` methods for the `Store` associated with that graph will return the same value.

In `Graph` there's a different `getSchema` method which confusingly calls `getOriginalSchema` on the graph's `Store`.

This ticket was raised because of problems fetching schemas with Federated and Proxy Stores. The current implementation of these stores contain overridden methods for `getSchema` but not `getOriginalSchema`. It's likely that with certain combinations of graphs and stores, the `originalSchema` field could remain `null` or be outdated. This could cause problems with the getSchema operation when used directly on the store (not wrapped) and differences between using a `Store` directly and using it through a `Graph`.

**I suggest this ticket be closed** because `getSchema` cannot be removed and was marked as deprecated by mistake. New tickets should be raised to:

- Remove the deprecated annotation and improve the Javadoc for all schema associated methods.
- Investigate and fix any problems with Federated and Proxy Store use of `getSchema`/`getOriginalSchema`. This might be as simple as adding overridden methods for `getOriginalSchema`.
