### ISSUE TITLE
First properties are inconsistently aggregated in Accumulo

### ISSUE THREAD

**Issue by t92549** [gchq/Gaffer#2891]
**Describe the bug**
Properties with the aggregationFunction of First seem to return inconsistent results when updated multiple times in an Accumulo store. 

**To Reproduce**
1. Have an AccumuloStore with a schema where a property is aggregated with First
2. AddElements and you should have the value returned by GetElements
3. Perform multiple AddElements and keep track of the order that you added them in
4. Perform GetElements and note that the resulting property will change inconsistently

**Expected behavior**
What should happen for First is that the most recent value is returned. 

**Additional context**
This leads to occasions where the First function provides inconsistent results, which should never happen. Other pure functions like Max are deterministic and will always return the max value immediately. I worry that due to how the scanning is working and applying iterators, First will produce non deterministic results and that sometimes data will be lost. 
The same is also maybe true of Last which should always retain the oldest value.

An experiment/test should be made in order to try and reliably recreate this issue

**Comment by GCHQDeveloper314** [comment]
@n3101 As I currently understand it, this is a problem with Accumulo's behaviour when using `First` in certain situations. I'll explain why.

As seen in the tests for `First`, [all it does it take a list of object and returns the first one](https://github.com/gchq/koryphe/blob/9e83b6896cec80cb15a306467302a1600b6b2d66/core/src/test/java/uk/gov/gchq/koryphe/impl/function/FirstItemTest.java#L73). So with `[1, 2, 3]` it always returns `1`.

When an element (with a property using `First` as the aggregation function) which already exists in Gaffer is added again, the intention is for the existing value of the property to be replaced by the new value. This is the use case which raised the problem in this issue.

This use of `First` works because the Gaffer Accumulo iterators must be supplying a list of `[newValue, existingValue]` to the `First` binary operator, causing the newest value to always be used as it is first in this list. The application of the operator is done by the Gaffer Accumulo iterators whenever there's a relevant scan or a compaction.

This use of `First` (which is not documented anywhere) relies on the binary operator being applied in the order of insertion. Such that the last (most recent) element inserted is the final one to have the comparison applied and is therefore the version which is used to replace the existing value.

If a single update is made, then there are only two copies of the element present in Accumulo - the existing element and the new version which has been inserted. When a scan or compaction occurs there is only one possible order for the list (`[newValue, existingValue]`). When the new value was inserted is irrelevant.

If multiple versions of the element are inserted, but the time when they were inserted **is not used** to order the application of the binary operator, then there's nothing to ensure the last inserted element is the one which is used to replace the existing value. The existing value then appears to be replaced by one of the new values at random - **the problem in this issue**.

In a given time window, this problem occurs only when there are multiple updates made to the same element, never if there is a single update. The time window matters because when a compaction occurs the updates processed and the existing value replaced. In practice, this problem will never be experienced if an element is updated only once between each compaction. The frequency of compactions will depend on the rate of data ingest and other factors.

_This apparent lack of ordering elements by insertion time is probably part of Accumulo's behaviour, but this hasn't been confirmed._

If an AddElements contained two updates to the same element property, the value used for the update would be definitely be random because if "two inserts are made into Accumulo with the same rowID, column, and timestamp, then the behavior is non-deterministic" ([from the Accumulo docs](https://accumulo.apache.org/docs/2.x/getting-started/table_configuration#versioning-iterators-and-timestamps)). This confirms the problem only when multiple updates have identical timestamps. Further investigation is needed to confirm how the ordering is done when the timestamps are not the same.

**Comment by n3101** [comment]
@GCHQDeveloper314 Thanks for setting this out. For work estimation purposes - do you have any ideas for a fix, or does this still need to be worked out?
