### ISSUE TITLE
ProxyStore getTraits is static

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2917]
**Describe the bug**
from #2581 changes the GetTraits Handler get traits from remote store. this is set/static at time of creation. this will not work if the Proxy is pointed towards a FederatedStore

**Expected behavior**
The ProxyStore should get updated traits for a remote FederatedStore when traits are added or removed.

**Additional context**
Likely a new Proxy GetTraitsHandler is required.

**Comment by GCHQDeveloper314** [comment]
There is a extra complication because of how the Federated Store now handles traits. Previously, when the `getTraits` method existed the Federated Store returned `ALL_TRAITS` as its traits when using this method, it did not ask subgraphs for their traits at all. When the `GetTraits` Operation is used, this is federated to subgraphs with the intersection of traits returned.

There was not previously a capacity for a proxy to cause a loop by fetching remote traits because the `getTraits` method stopped at Federated Store. A loop is created if the proxy creates a new operation to ask for traits from the remote graph (which points back to itself via a Federated Store) every time it itself receives a `GetTraits` operation.

By using a new operation in the Proxy Store to ask for traits, a Federated Store is unable to detect that a loop has occurred. This can be corrected by reusing the incoming operation inside the Proxy, such that when a getTraits is looped back to the Federated Store which forwarded it, the "already processed" marker will be detected and the loop stopped. This has been done in #2919. 

**The problem in this issue would not exit at all** if the Proxy Store didn't need to remove the `VISIBILITY` trait from the remote store's responses. This is done because the Proxy Store doesn't support `VISIBILITY`, if it did support it then all of the code to handle this special case could be removed and `GetTraits` operations could be proxied in the same way as everything else. This lack of support is because it cannot handle and doesn't forward `Context`, this would be fixed in #2879.

**Comment by t92549** [comment]
Closed by https://github.com/gchq/Gaffer/pull/2919
