### ISSUE TITLE
Improve Federated Store Tests to make use of properties file

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/Gaffer#3158]
**Describe the enhancement you'd like**
Throughout the Federated Store there are multiple instances of this code pattern in many places in various files:
https://github.com/gchq/Gaffer/blob/ac602892435bdd0180f783c80f774149f50eb7f0/store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreVisibilityTest.java#L71-L72

These can all be replaced with a single line which loads a generic Federated Store config properties file (from test/resources) using the `getFederatedStorePropertiesWithHashMapCache` utility method from `FederatedStoreTestUtil`.

**Why do you want this feature?**
To simplify the tests for this module.

**Comment by nine03** [comment]
Hello, I forked and cloned the repository using SourceTree in order to resolve this issue. When I opened the code related to the issue, there were import errors. I would like to ask for some advice on how to handle these import errors.

![1](https://github.com/gchq/Gaffer/assets/60682087/4fe98951-8fa2-46f7-b8b4-98ed7ce90b22)

**Comment by GCHQDeveloper314** [comment]
Depending on the IDE used, it might require you to run a full build locally first. You can do this with `mvn clean install -Pquick`. If you are using Windows then some tests may fail to run (Hadoop/Accumulo) as they are not compatible with Windows.

**Comment by nine03** [comment]
Thank you for the advice. The tests failed in my Windows IntelliJ environment, so I am planning to switch to an Ubuntu environment to continue working.

**Comment by nine03** [comment]
![image](https://github.com/gchq/Gaffer/assets/60682087/d6fcb982-8838-460c-8bbf-ce15535379b3)

Thank you for the advice. I was able to build successfully using the ```mvn clean install -Pquick``` command you suggested. The problem is that when I tried to run the FederatedStoreVisibilityTest test code, it failed the tests as shown in the screenshot. I installed Ubuntu and ran the tests there, but I'm still getting the same results as shown in the image.

![image](https://github.com/gchq/Gaffer/assets/60682087/fcc7bc8a-60d8-47ca-a50b-bb4dd905946b)

**Comment by GCHQDeveloper314** [comment]
Ensure you have Java 8 installed and configured as the Java version to use in your IDE. I did some brief research which indicates that that zookeeper error is caused by using a recent Java version. Java 11 is the latest which is officially supported, but 8 is recommended for now.

**Comment by nine03** [comment]
I have resolved this issue and have created a pull request.
Could you kindly review and address it when you have the chance?

**Comment by nine03** [comment]
I have resolved this issue and have created a pull request.
Could you kindly review and address it when you have the chance?

**Comment by nine03** [comment]
I have resolved this issue and have created a pull request.
Could you kindly review and address it when you have the chance?

**Comment by nine03** [comment]
@GCHQDeveloper314 
I have resolved this issue and have created a pull request.
Could you kindly review and address it when you have the chance?
