### ISSUE TITLE
Remove use of gafferStoreUtils table

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#370]
The gafferStoreUtils table is no longer being used. 
All references to it in the code base should be removed.

**Comment by gaffer01** [comment]
Could this table be used to check that a table has been initialised by Gaffer? There have been instances where a table has been created in Accumulo manually and then Gaffer data has been put in, and the user isn't aware that this won't function correctly because the correct iterators, etc., have not been applied.

**Comment by p013570** [comment]
It could be. However there must be a simpler way of doing it - perhaps by somehow setting a property on the table when a table is created by Gaffer.

**Comment by gaffer01** [comment]
True. We could insert a key with some very obscure string as the column family and record in the value when the table was created, and then check for the existence of that before doing any operation on the graph.

**Comment by t616178** [comment]
This has been merged into develop.
