### ISSUE TITLE
Review Accumulo iterator stack

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#406]
We should review the current set of iterators in the Accumulo store, with the aim of:
- Ensuring that the current stack of iterators is properly documented somewhere.
- Reviewing whether any of the iterators needlessly deserialise key-values to elements and reserialise them back again (e.g. if a filter always returns true, there's no point in deserialising and reserialising).
- Look for opportunities to rationalise or merge iterators, e.g. could all current pre-aggregation iterators be done in one iterator to avoid multiple deserialisation and reserialisation?
- Review whether we should be lazily deserialising key-values to elements so that parts are only deserialised as necessary to run a filter or transform.

**Comment by p013570** [comment]
When I was implementing the iterators in the HBase Store I implemented them as 1 big coprocessor. This removes the need to deserialise and serialise multiple times. Perhaps we could do a similar thing in the Accumulo Store?

**Comment by p013570** [comment]
From doing some simple analysis the changes I have started to make look to the accumulo iterators will result in a significant reduction in query times.

**Comment by p013570** [comment]
# Migration Steps

This issue doesn't actually require you to make any changes. However, if you make a few minor changes it could make a bit difference to your performance if you are running on Accumulo. It is really worth reading the optimisations below as in some cases it can easily halve your query times.

These are the changes that were actually made in the issue:
- ValidatorFilter, ElementPreAggregationFilter and ElementPostAggregationFilter accumulo iterators are only applied if they are actually required. I.e there are filters defined in the schema/view.
- ValidatorFilter, ElementPreAggregationFilter and ElementPostAggregationFilter iterators now lazily deserialise the different accumulo columns. So if you only filter on groupBy properties then we don't need to deserialise all the properties in the Value, just the ones in the column qualifier.
- The accumulo handler for GetAdjacentIds now only deserialisers the rowId and extracts the destination. Unless the user provides post transform filters.
- Tidied up some other classes.

Here are some optimisations when using Accumulo:

You can optimise your ValidatorFilter iterator, by removing any unnecessary validation. You can do most of the validation you require in your elements in your ElementGenerator class. The validation you provide in the schema should be just the validation that you actually have to have, because this will be run A LOT: major/minor compactions and for every query. If you can, just validate properties that are in the groupBy, this will mean that the ValidatorFilter doesn't need to deserialise the entire Value to perform the validation.

When doing queries, if you don't specify Pre or Post Aggregation filters then these iterators will be skipped. So, if applicable, you will save time if you put all your filtering in Pre or Post (in some cases this isn't possible). If you want to to a time window query and you're timestamp is a groupBy property then your query will be really fast as again it doesn't need to deserialise the entire Value, just the column qualifier.

When doing GetAdjacentIds, try and avoid using PostTransformFilters as if you don't specify these then the final part of the query won't need to deserialise the properties it can just extract the destination off the edge.

**Comment by p013570** [comment]
Merged into develop.
