### ISSUE TITLE
Remove spark dependencies from core operation and serialisation bundles

### ISSUE THREAD

**Issue by a09631** [gchq/Gaffer#486]
There are some dependencies in the operations and serialisation libraries (as examples) such as Spark, which include extra transitive dependencies.  These should be removed, and these specific operations moved in to their own bundle.  This may also apply to hfs specific operations.

**Comment by p013570** [comment]
The spark operations may need refactoring in the future to avoid creating a large number of operations similar to GetElements in different formats/wrappers. For example, we could make use of the Export operation and create different spark exporters.

For the time being I think I would be best to just move the spark code into separate modules.
Spark operations should be moved into a new module: spark-operation-lib

The accumulo spark operation handlers should be moved into a new module: accumulo-spark-operation-handlers

Then to use accumulo with spark users would need to add a dependency on accumulo-spark-operation-handlers and create an AccumuloStore with a operationsDeclarations.json file similar to [this](https://github.com/gchq/Gaffer/blob/master/gaffer-core/store/src/test/resources/operationDeclarations.json) where the spark operations and their handlers are registered.

**Comment by gaffer01** [comment]
The Spark-related code is currently split across the modules in the same way as everything else - operations in the operations module, Accumulo handlers in the Accumulo module, etc.

This issue is not specific to Spark. We have a dependency on the library that provides `HyperLogLogPlus` in the serialisation library for example. Any code that uses the Accumulo store has dependencies on Hadoop which has dependencies on many things.

What do we use to decide what belongs in its own module and what doesn't?

Would we have a separate module for the `HyperLogLogPlus` serialiser for example?

Just want to see if we can establish general principles before making Spark a special case.

If Spark-related code is moved to its own module, I'd favour having one Spark module with a submodule for operations, and a submodule for the Accumulo handlers, etc.

Also see the comment in #535 about why it may be tricky to make Spark just a place where data is exported to.

**Comment by p013570** [comment]
Good spot - I had forgotten about the HyperLogLogPlus dependency. Yes I think we need to follow the same pattern for that too. So something like this:

```
    library
        - core-library
            - core-function
            - core-operation
            - core-serialisation
        - spark-library
            - spark-function
            - spark-operation
            - spark-serialisation
            - spark-accumulo-operation-handlers
        - hyperloglogplus
            - hyperloglogplus-function
            - hyperloglogplus-operation
            - hyperloglogplus-serialisation
```

So for example of you want all of spark you can depend on the spark library parent pom.

**Comment by p013570** [comment]
# Migration steps

The libraries module has been split up into core, hdfs, spark and sketches. To use these now you will can do the following:

```xml
 <dependency>
  <groupId>uk.gov.gchq.gaffer</groupId>
  <artifactId>core-library-all</artifactId>
  <version>${gaffer.version}</version>
</dependency>
```

The names of the iterator jars have changed so it is consistent for all libraries - just has a classifier name of 'shaded'.

Spark is now separate from the accumulo store so if you require spark you will need to register the operations - see the spark README in the spark library module.

**Comment by t616178** [comment]
Merged into develop.
