### ISSUE TITLE
Refactor Add and Get element operations

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#535]
Currently we have a couple versions of AddElements - AddElements and AddElementsFromHdfs.
It would be neater to have an AddElements operation that takes a Source object, describing where the elements are coming from and how to add them to Gaffer.

Similar we have a few GetElements - e.g GetElements, GetJavaRDDOfAllElements, GetRDDOfElements, GetDataFrameOfElements.
It would be neater to have a GetElements operation that takes a Destination object, describing the format of the result.

This is a similar pattern to the Export operation with an Exporter. The Export operation could be deleted and these Exporters could be changed to work with GetElements and a Destination.

**Comment by gaffer01** [comment]
It's worth noting that some of these operations (specifically the Spark ones) can't be implemented by just taking the results of say `GetElements` and converting the results into the right format. This is because the way the results are obtained is important - the Spark ones should **not** be implemented by taking an iterable of results that goes to a client and then converting that into an RDD, the extraction of the results from Accumulo needs to be done in parallel taking into account locality, etc. This is why it uses the `InputFormat` behind the scenes.

Another example is that the operation that returns a `Dataframe` doesn't actually return any data - no data is returned until subsequent queries are executed against the dataframe.

The goal of this issue is good. But it's not as simple as just specifying an output destination/format for the results of the standard get operations.

**Comment by t616178** [comment]
Closing due to @gaffer01 's comments.
