### ISSUE TITLE
Add more javadoc

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#910]
There are some areas of the framework that could really do with some more javadoc.

**Comment by m607123** [comment]
Any particular areas of focus / high priority that would benefit from this?

**Comment by p013570** [comment]
Any class that is public facing should have a class javadoc. Any complex methods in those classes should also have a javadoc.

We can all collaborate on this issue and work on the same branch:
gh-910-javadoc

**Comment by m607123** [comment]
This is by no means an exhaustive list (otherwise it'd be quite large), but below are some classes that I thought might be a good place to start.

## No Javadoc
ElementFilter
SchemaEntityDefinition
SchemaElementDefinition
User
_All of the Ordered Serialisers_
OverwritingException (in store/exception)
_All of store/library_
OperationChainValidator
SchemaOptimiser

## Sparse - Few explanations, or unclear
ElementAggregator
TypeDefinition

## Needs Elaboration - Perhaps the odd method could do with more verbose explanation
SchemaElementDefinition
SchemaElementDefinitionValidator
Schema (eg the merge() method)

**Comment by t616178** [comment]
The main outstanding Javadoc omissions are now in the store implementations.

**Comment by p013570** [comment]
Merged into develop.
