### ISSUE TITLE
The job tracker will not be updated if an Error is thrown

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#976]
The job tracker should be updated after an operation chain has completed or any error has occurred during execution of the operation chain.

However, the try catch block only catches Exception objects not Error objects so the job tracker will never be update in the event an Error occurs such as OutOfMemoryError.

See Store execute and executeJob methods.

**Comment by m55624** [comment]
Catching any Error could cause more issues.  All sorts of Errors can be thrown at any time dependant on running environments etc.  If we try to catch an Error that stops the JobTracker update from running correctly we could end up with more different issues.  In a standard case if any Error is thrown it should have effect immediately and not be handled.

**Comment by gchqdev03** [comment]
On the other hand a user needs to know if there was a problem. For example we were running a long running job and the job status wasn't getting updated. It was probably due to an out of memory error but the job status just stayed as running. It would be useful, whenever possible to show that the job failed

**Comment by t616178** [comment]
Merged into develop.
